# Generated by Django 5.0.1 on 2024-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_deliverylog_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='clients',
            field=models.ManyToManyField(related_name='mailing_lists', to='mailing_app.client'),
        ),
    ]
