# Generated by Django 5.0.1 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0005_mailinglist_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='name_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
