# Generated by Django 5.0.1 on 2024-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0006_mailinglist_name_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='message',
            field=models.ManyToManyField(related_name='mailing_lists', to='mailing_app.message'),
        ),
    ]
