# Generated by Django 5.0.1 on 2024-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0007_remove_message_mailing_list_mailinglist_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name_latter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
