# Generated by Django 5.0.1 on 2024-01-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0008_message_name_latter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name_latter',
            new_name='name_letter',
        ),
    ]
