# Generated by Django 4.2.9 on 2024-01-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0013_deliverylog_status_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylog',
            name='attempt_status',
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status_attempt',
            field=models.BooleanField(default=False, verbose_name='status attempt'),
        ),
    ]
