# Generated by Django 4.2.9 on 2024-01-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0014_remove_deliverylog_attempt_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingList',
            new_name='MailingService',
        ),
        migrations.RenameField(
            model_name='deliverylog',
            old_name='status_attempt',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mailing_list_message',
        ),
        migrations.AddField(
            model_name='message',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing_app.mailingservice', verbose_name='рассылка'),
        ),
    ]
