# Generated by Django 4.2.9 on 2024-01-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0015_rename_mailinglist_mailingservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingservice',
            name='name_list',
        ),
    ]
