# Generated by Django 4.2.9 on 2024-01-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
