# Generated by Django 4.2.9 on 2024-01-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Article contents')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='Image')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('views_count', models.IntegerField(default=0, verbose_name='number of views')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
